#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Sim\Command\CleanWebpackFiles;
use Sim\Command\MoveWebpackFiles;
use App\Bootstrap;
use Symfony\Component\Console\Application;

$bootstrap = new Bootstrap(false);
$application = new Application();

// ... register commands

$application->add(new CleanWebpackFiles());
$application->add(new MoveWebpackFiles());
$application->run();
